{"uid":"a8ee67a9d230e565","name":"잘못된 ID,PW 입력 시 로그인이 실패하는지 확인","fullName":"src.tests.ui_tests.test_ui_login#test_login","historyId":"98e8f149c7227721782a965f730ba74a","time":{"start":1746425422300,"stop":1746425429810,"duration":7510},"status":"failed","statusMessage":"Failed: ❌ 로그인 실패 :Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"pw\"]\"}\n  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x5646f38307fa <unknown>\n#1 0x5646f32d4e90 <unknown>\n#2 0x5646f3326870 <unknown>\n#3 0x5646f3326a61 <unknown>\n#4 0x5646f3374cb4 <unknown>\n#5 0x5646f334c26d <unknown>\n#6 0x5646f3372135 <unknown>\n#7 0x5646f334c013 <unknown>\n#8 0x5646f3318b3b <unknown>\n#9 0x5646f33197a1 <unknown>\n#10 0x5646f37f5b9b <unknown>\n#11 0x5646f37f9a8a <unknown>\n#12 0x5646f37dd912 <unknown>\n#13 0x5646f37fa604 <unknown>\n#14 0x5646f37c274f <unknown>\n#15 0x5646f381e678 <unknown>\n#16 0x5646f381e856 <unknown>\n#17 0x5646f382f666 <unknown>\n#18 0x7fbb6978a1f5 <unknown>","statusTrace":"src/tests/ui_tests/test_ui_login.py:23: in test_login\n    login_password_input = driver.find_element(By.ID, \"pw\")\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:917: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:448: in execute\n    self.error_handler.check_response(response)\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py:232: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"pw\"]\"}\nE     (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE   Stacktrace:\nE   #0 0x5646f38307fa <unknown>\nE   #1 0x5646f32d4e90 <unknown>\nE   #2 0x5646f3326870 <unknown>\nE   #3 0x5646f3326a61 <unknown>\nE   #4 0x5646f3374cb4 <unknown>\nE   #5 0x5646f334c26d <unknown>\nE   #6 0x5646f3372135 <unknown>\nE   #7 0x5646f334c013 <unknown>\nE   #8 0x5646f3318b3b <unknown>\nE   #9 0x5646f33197a1 <unknown>\nE   #10 0x5646f37f5b9b <unknown>\nE   #11 0x5646f37f9a8a <unknown>\nE   #12 0x5646f37dd912 <unknown>\nE   #13 0x5646f37fa604 <unknown>\nE   #14 0x5646f37c274f <unknown>\nE   #15 0x5646f381e678 <unknown>\nE   #16 0x5646f381e856 <unknown>\nE   #17 0x5646f382f666 <unknown>\nE   #18 0x7fbb6978a1f5 <unknown>\n\nDuring handling of the above exception, another exception occurred:\nsrc/tests/ui_tests/test_ui_login.py:37: in test_login\n    pytest.fail(f\"❌ 로그인 실패 :{str(e)}\")\nE   Failed: ❌ 로그인 실패 :Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"pw\"]\"}\nE     (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE   Stacktrace:\nE   #0 0x5646f38307fa <unknown>\nE   #1 0x5646f32d4e90 <unknown>\nE   #2 0x5646f3326870 <unknown>\nE   #3 0x5646f3326a61 <unknown>\nE   #4 0x5646f3374cb4 <unknown>\nE   #5 0x5646f334c26d <unknown>\nE   #6 0x5646f3372135 <unknown>\nE   #7 0x5646f334c013 <unknown>\nE   #8 0x5646f3318b3b <unknown>\nE   #9 0x5646f33197a1 <unknown>\nE   #10 0x5646f37f5b9b <unknown>\nE   #11 0x5646f37f9a8a <unknown>\nE   #12 0x5646f37dd912 <unknown>\nE   #13 0x5646f37fa604 <unknown>\nE   #14 0x5646f37c274f <unknown>\nE   #15 0x5646f381e678 <unknown>\nE   #16 0x5646f381e856 <unknown>\nE   #17 0x5646f382f666 <unknown>\nE   #18 0x7fbb6978a1f5 <unknown>","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"Failed: ❌ 로그인 실패 :Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"pw\"]\"}\n  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x5646f38307fa <unknown>\n#1 0x5646f32d4e90 <unknown>\n#2 0x5646f3326870 <unknown>\n#3 0x5646f3326a61 <unknown>\n#4 0x5646f3374cb4 <unknown>\n#5 0x5646f334c26d <unknown>\n#6 0x5646f3372135 <unknown>\n#7 0x5646f334c013 <unknown>\n#8 0x5646f3318b3b <unknown>\n#9 0x5646f33197a1 <unknown>\n#10 0x5646f37f5b9b <unknown>\n#11 0x5646f37f9a8a <unknown>\n#12 0x5646f37dd912 <unknown>\n#13 0x5646f37fa604 <unknown>\n#14 0x5646f37c274f <unknown>\n#15 0x5646f381e678 <unknown>\n#16 0x5646f381e856 <unknown>\n#17 0x5646f382f666 <unknown>\n#18 0x7fbb6978a1f5 <unknown>","statusTrace":"src/tests/ui_tests/test_ui_login.py:23: in test_login\n    login_password_input = driver.find_element(By.ID, \"pw\")\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:917: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:448: in execute\n    self.error_handler.check_response(response)\n/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py:232: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"pw\"]\"}\nE     (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE   Stacktrace:\nE   #0 0x5646f38307fa <unknown>\nE   #1 0x5646f32d4e90 <unknown>\nE   #2 0x5646f3326870 <unknown>\nE   #3 0x5646f3326a61 <unknown>\nE   #4 0x5646f3374cb4 <unknown>\nE   #5 0x5646f334c26d <unknown>\nE   #6 0x5646f3372135 <unknown>\nE   #7 0x5646f334c013 <unknown>\nE   #8 0x5646f3318b3b <unknown>\nE   #9 0x5646f33197a1 <unknown>\nE   #10 0x5646f37f5b9b <unknown>\nE   #11 0x5646f37f9a8a <unknown>\nE   #12 0x5646f37dd912 <unknown>\nE   #13 0x5646f37fa604 <unknown>\nE   #14 0x5646f37c274f <unknown>\nE   #15 0x5646f381e678 <unknown>\nE   #16 0x5646f381e856 <unknown>\nE   #17 0x5646f382f666 <unknown>\nE   #18 0x7fbb6978a1f5 <unknown>\n\nDuring handling of the above exception, another exception occurred:\nsrc/tests/ui_tests/test_ui_login.py:37: in test_login\n    pytest.fail(f\"❌ 로그인 실패 :{str(e)}\")\nE   Failed: ❌ 로그인 실패 :Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"pw\"]\"}\nE     (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE   Stacktrace:\nE   #0 0x5646f38307fa <unknown>\nE   #1 0x5646f32d4e90 <unknown>\nE   #2 0x5646f3326870 <unknown>\nE   #3 0x5646f3326a61 <unknown>\nE   #4 0x5646f3374cb4 <unknown>\nE   #5 0x5646f334c26d <unknown>\nE   #6 0x5646f3372135 <unknown>\nE   #7 0x5646f334c013 <unknown>\nE   #8 0x5646f3318b3b <unknown>\nE   #9 0x5646f33197a1 <unknown>\nE   #10 0x5646f37f5b9b <unknown>\nE   #11 0x5646f37f9a8a <unknown>\nE   #12 0x5646f37dd912 <unknown>\nE   #13 0x5646f37fa604 <unknown>\nE   #14 0x5646f37c274f <unknown>\nE   #15 0x5646f381e678 <unknown>\nE   #16 0x5646f381e856 <unknown>\nE   #17 0x5646f382f666 <unknown>\nE   #18 0x7fbb6978a1f5 <unknown>","steps":[],"attachments":[{"name":"Failure Screenshot","type":"image/png","size":0},{"name":"stdout","type":"text/plain","size":0}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"feature","value":"예외 케이스"},{"name":"story","value":"잘못된 ID,PW 입력"},{"name":"parentSuite","value":"src.tests.ui_tests"},{"name":"suite","value":"test_ui_login"},{"name":"host","value":"4a4b32d0ab0e"},{"name":"thread","value":"15-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"src.tests.ui_tests.test_ui_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"a8ee67a9d230e565.json","parameterValues":[]}