{"uuid": "a053b63d-5806-4d6c-b903-1bdff461d09d", "children": ["250921ad-ffb8-42e4-9929-1e51ccda745e"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x564833d94ffa <unknown>\n#1 0x564833853970 <unknown>\n#2 0x5648338a5385 <unknown>\n#3 0x5648338a55b1 <unknown>\n#4 0x5648338f43c4 <unknown>\n#5 0x5648338cb2bd <unknown>\n#6 0x5648338f170c <unknown>\n#7 0x5648338cb063 <unknown>\n#8 0x564833897328 <unknown>\n#9 0x564833898491 <unknown>\n#10 0x564833d5c42b <unknown>\n#11 0x564833d602ec <unknown>\n#12 0x564833d43a22 <unknown>\n#13 0x564833d60e64 <unknown>\n#14 0x564833d27bef <unknown>\n#15 0x564833d83558 <unknown>\n#16 0x564833d83736 <unknown>\n#17 0x564833d93e76 <unknown>\n#18 0x7f6e9229caa4 <unknown>\n#19 0x7f6e92329c3c <unknown>\n\n", "trace": "  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/ui_tests/conftest.py\", line 36, in driver\n    raise e\n  File \"/home/runner/work/QATEST/QATEST/src/tests/ui_tests/conftest.py\", line 30, in driver\n    search_box = WebDriverWait(driver, 10).until(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1742981773284, "stop": 1742981786734}], "start": 1742981773284, "stop": 1742981786741}