{"uuid": "0eea57ac-5f87-44bc-b3b2-f2ebec4296ce", "children": ["f3433211-52db-43d6-8a5f-f02099af86f8"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//input[@id='gnb_search']\"}\n  (Session info: chrome=134.0.6998.88); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x555ef7756ffa <unknown>\n#1 0x555ef7215970 <unknown>\n#2 0x555ef7267385 <unknown>\n#3 0x555ef72675b1 <unknown>\n#4 0x555ef72b63c4 <unknown>\n#5 0x555ef728d2bd <unknown>\n#6 0x555ef72b370c <unknown>\n#7 0x555ef728d063 <unknown>\n#8 0x555ef7259328 <unknown>\n#9 0x555ef725a491 <unknown>\n#10 0x555ef771e42b <unknown>\n#11 0x555ef77222ec <unknown>\n#12 0x555ef7705a22 <unknown>\n#13 0x555ef7722e64 <unknown>\n#14 0x555ef76e9bef <unknown>\n#15 0x555ef7745558 <unknown>\n#16 0x555ef7745736 <unknown>\n#17 0x555ef7755e76 <unknown>\n#18 0x7f679bc9caa4 <unknown>\n#19 0x7f679bd29c3c <unknown>\n\n", "trace": "  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/ui_tests/conftest.py\", line 29, in driver\n    driver.find_element(By.XPATH,\"//input[@id='gnb_search']\").click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 770, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742972469678, "stop": 1742972470708}], "start": 1742972469678, "stop": 1742972470732}