{"uuid": "f6f02f03-8d13-421e-a9e0-d6a8747a77e5", "children": ["c0d11cc5-d4ba-420a-8784-88f59c73bc33"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x556b73423ffa <unknown>\n#1 0x556b72ee2970 <unknown>\n#2 0x556b72f34385 <unknown>\n#3 0x556b72f345b1 <unknown>\n#4 0x556b72f833c4 <unknown>\n#5 0x556b72f5a2bd <unknown>\n#6 0x556b72f8070c <unknown>\n#7 0x556b72f5a063 <unknown>\n#8 0x556b72f26328 <unknown>\n#9 0x556b72f27491 <unknown>\n#10 0x556b733eb42b <unknown>\n#11 0x556b733ef2ec <unknown>\n#12 0x556b733d2a22 <unknown>\n#13 0x556b733efe64 <unknown>\n#14 0x556b733b6bef <unknown>\n#15 0x556b73412558 <unknown>\n#16 0x556b73412736 <unknown>\n#17 0x556b73422e76 <unknown>\n#18 0x7fdcc569caa4 <unknown>\n#19 0x7fdcc5729c3c <unknown>\n\n", "trace": "  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/ui_tests/conftest.py\", line 30, in driver\n    WebDriverWait(driver, 10).until(\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1743000370787, "stop": 1743000383185}], "start": 1743000370787, "stop": 1743000383191}