{"uuid": "667c30b6-b22c-4cac-8017-6ec3c037ecd1", "children": ["1c62fd2e-ec7a-4af4-9f1b-14a45311eecc"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5571ba938ffa <unknown>\n#1 0x5571ba3f7970 <unknown>\n#2 0x5571ba449385 <unknown>\n#3 0x5571ba4495b1 <unknown>\n#4 0x5571ba4983c4 <unknown>\n#5 0x5571ba46f2bd <unknown>\n#6 0x5571ba49570c <unknown>\n#7 0x5571ba46f063 <unknown>\n#8 0x5571ba43b328 <unknown>\n#9 0x5571ba43c491 <unknown>\n#10 0x5571ba90042b <unknown>\n#11 0x5571ba9042ec <unknown>\n#12 0x5571ba8e7a22 <unknown>\n#13 0x5571ba904e64 <unknown>\n#14 0x5571ba8cbbef <unknown>\n#15 0x5571ba927558 <unknown>\n#16 0x5571ba927736 <unknown>\n#17 0x5571ba937e76 <unknown>\n#18 0x7fc75a89caa4 <unknown>\n#19 0x7fc75a929c3c <unknown>\n\n", "trace": "  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/conftest.py\", line 37, in driver\n    WebDriverWait(driver, 10).until(\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1743026892850, "stop": 1743026905651}], "start": 1743026892850, "stop": 1743026905657}