{"uuid": "a7eae61a-e8cc-4956-abe3-ec8dade77111", "children": ["afce8545-2fc2-4298-a995-f10f19f30697"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x556643222ffa <unknown>\n#1 0x556642ce1970 <unknown>\n#2 0x556642d33385 <unknown>\n#3 0x556642d335b1 <unknown>\n#4 0x556642d823c4 <unknown>\n#5 0x556642d592bd <unknown>\n#6 0x556642d7f70c <unknown>\n#7 0x556642d59063 <unknown>\n#8 0x556642d25328 <unknown>\n#9 0x556642d26491 <unknown>\n#10 0x5566431ea42b <unknown>\n#11 0x5566431ee2ec <unknown>\n#12 0x5566431d1a22 <unknown>\n#13 0x5566431eee64 <unknown>\n#14 0x5566431b5bef <unknown>\n#15 0x556643211558 <unknown>\n#16 0x556643211736 <unknown>\n#17 0x556643221e76 <unknown>\n#18 0x7fd79ba9caa4 <unknown>\n#19 0x7fd79bb29c3c <unknown>\n\n", "trace": "  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/ui_tests/conftest.py\", line 30, in driver\n    WebDriverWait(driver, 10).until(\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1743024825360, "stop": 1743024837300}], "start": 1743024825360, "stop": 1743024837306}