{"uuid": "d77662b5-59a9-438f-9ba6-fee6a88cf2bd", "children": ["914be4f1-a882-45ff-9062-1d854fa2673c"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5610fc694ffa <unknown>\n#1 0x5610fc153970 <unknown>\n#2 0x5610fc1a5385 <unknown>\n#3 0x5610fc1a55b1 <unknown>\n#4 0x5610fc1f43c4 <unknown>\n#5 0x5610fc1cb2bd <unknown>\n#6 0x5610fc1f170c <unknown>\n#7 0x5610fc1cb063 <unknown>\n#8 0x5610fc197328 <unknown>\n#9 0x5610fc198491 <unknown>\n#10 0x5610fc65c42b <unknown>\n#11 0x5610fc6602ec <unknown>\n#12 0x5610fc643a22 <unknown>\n#13 0x5610fc660e64 <unknown>\n#14 0x5610fc627bef <unknown>\n#15 0x5610fc683558 <unknown>\n#16 0x5610fc683736 <unknown>\n#17 0x5610fc693e76 <unknown>\n#18 0x7efdac69caa4 <unknown>\n#19 0x7efdac729c3c <unknown>\n\n", "trace": "  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/ui_tests/conftest.py\", line 29, in driver\n    WebDriverWait(driver, 10).until(\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1742995465090, "stop": 1742995489031}], "start": 1742995465090, "stop": 1742995489088}