{"uid":"6b6912f2f7a5fd76","name":"잘못된 ID,PW 입력 시 로그인이 실패하는지 확인","fullName":"src.tests.ui_tests.test_ui_login#test_login","historyId":"98e8f149c7227721782a965f730ba74a","time":{"start":1745926044572,"stop":1745926046696,"duration":2124},"status":"failed","statusMessage":"Failed: ❌ 로그인 실패 :Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[contains(text(),'로그인')]\"}\n  (Session info: chrome=135.0.7049.95); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x55cb83adc75a <unknown>\n#1 0x55cb8358f4b0 <unknown>\n#2 0x55cb835e09b3 <unknown>\n#3 0x55cb835e0ba1 <unknown>\n#4 0x55cb8362f1f4 <unknown>\n#5 0x55cb836065bd <unknown>\n#6 0x55cb8362c5e0 <unknown>\n#7 0x55cb83606363 <unknown>\n#8 0x55cb835d2d63 <unknown>\n#9 0x55cb835d39c1 <unknown>\n#10 0x55cb83aa1a6b <unknown>\n#11 0x55cb83aa5951 <unknown>\n#12 0x55cb83a89b62 <unknown>\n#13 0x55cb83aa64c4 <unknown>\n#14 0x55cb83a6e13f <unknown>\n#15 0x55cb83aca6f8 <unknown>\n#16 0x55cb83aca8d6 <unknown>\n#17 0x55cb83adb5a6 <unknown>\n#18 0x7f75b8e9caa4 <unknown>\n#19 0x7f75b8f29c3c <unknown>","statusTrace":"src/tests/ui_tests/test_ui_login.py:16: in test_login\n    login_button = driver.find_element(By.XPATH, \"//a[contains(text(),'로그인')]\")\nvenv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:770: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\nvenv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:384: in execute\n    self.error_handler.check_response(response)\nvenv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:232: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[contains(text(),'로그인')]\"}\nE     (Session info: chrome=135.0.7049.95); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE   Stacktrace:\nE   #0 0x55cb83adc75a <unknown>\nE   #1 0x55cb8358f4b0 <unknown>\nE   #2 0x55cb835e09b3 <unknown>\nE   #3 0x55cb835e0ba1 <unknown>\nE   #4 0x55cb8362f1f4 <unknown>\nE   #5 0x55cb836065bd <unknown>\nE   #6 0x55cb8362c5e0 <unknown>\nE   #7 0x55cb83606363 <unknown>\nE   #8 0x55cb835d2d63 <unknown>\nE   #9 0x55cb835d39c1 <unknown>\nE   #10 0x55cb83aa1a6b <unknown>\nE   #11 0x55cb83aa5951 <unknown>\nE   #12 0x55cb83a89b62 <unknown>\nE   #13 0x55cb83aa64c4 <unknown>\nE   #14 0x55cb83a6e13f <unknown>\nE   #15 0x55cb83aca6f8 <unknown>\nE   #16 0x55cb83aca8d6 <unknown>\nE   #17 0x55cb83adb5a6 <unknown>\nE   #18 0x7f75b8e9caa4 <unknown>\nE   #19 0x7f75b8f29c3c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nsrc/tests/ui_tests/test_ui_login.py:35: in test_login\n    pytest.fail(f\"❌ 로그인 실패 :{str(e)}\")\nE   Failed: ❌ 로그인 실패 :Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[contains(text(),'로그인')]\"}\nE     (Session info: chrome=135.0.7049.95); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE   Stacktrace:\nE   #0 0x55cb83adc75a <unknown>\nE   #1 0x55cb8358f4b0 <unknown>\nE   #2 0x55cb835e09b3 <unknown>\nE   #3 0x55cb835e0ba1 <unknown>\nE   #4 0x55cb8362f1f4 <unknown>\nE   #5 0x55cb836065bd <unknown>\nE   #6 0x55cb8362c5e0 <unknown>\nE   #7 0x55cb83606363 <unknown>\nE   #8 0x55cb835d2d63 <unknown>\nE   #9 0x55cb835d39c1 <unknown>\nE   #10 0x55cb83aa1a6b <unknown>\nE   #11 0x55cb83aa5951 <unknown>\nE   #12 0x55cb83a89b62 <unknown>\nE   #13 0x55cb83aa64c4 <unknown>\nE   #14 0x55cb83a6e13f <unknown>\nE   #15 0x55cb83aca6f8 <unknown>\nE   #16 0x55cb83aca8d6 <unknown>\nE   #17 0x55cb83adb5a6 <unknown>\nE   #18 0x7f75b8e9caa4 <unknown>\nE   #19 0x7f75b8f29c3c <unknown>","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"driver","time":{"start":1745926043876,"stop":1745926044571,"duration":695},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"failed","statusMessage":"Failed: ❌ 로그인 실패 :Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[contains(text(),'로그인')]\"}\n  (Session info: chrome=135.0.7049.95); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x55cb83adc75a <unknown>\n#1 0x55cb8358f4b0 <unknown>\n#2 0x55cb835e09b3 <unknown>\n#3 0x55cb835e0ba1 <unknown>\n#4 0x55cb8362f1f4 <unknown>\n#5 0x55cb836065bd <unknown>\n#6 0x55cb8362c5e0 <unknown>\n#7 0x55cb83606363 <unknown>\n#8 0x55cb835d2d63 <unknown>\n#9 0x55cb835d39c1 <unknown>\n#10 0x55cb83aa1a6b <unknown>\n#11 0x55cb83aa5951 <unknown>\n#12 0x55cb83a89b62 <unknown>\n#13 0x55cb83aa64c4 <unknown>\n#14 0x55cb83a6e13f <unknown>\n#15 0x55cb83aca6f8 <unknown>\n#16 0x55cb83aca8d6 <unknown>\n#17 0x55cb83adb5a6 <unknown>\n#18 0x7f75b8e9caa4 <unknown>\n#19 0x7f75b8f29c3c <unknown>","statusTrace":"src/tests/ui_tests/test_ui_login.py:16: in test_login\n    login_button = driver.find_element(By.XPATH, \"//a[contains(text(),'로그인')]\")\nvenv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:770: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\nvenv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:384: in execute\n    self.error_handler.check_response(response)\nvenv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:232: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[contains(text(),'로그인')]\"}\nE     (Session info: chrome=135.0.7049.95); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE   Stacktrace:\nE   #0 0x55cb83adc75a <unknown>\nE   #1 0x55cb8358f4b0 <unknown>\nE   #2 0x55cb835e09b3 <unknown>\nE   #3 0x55cb835e0ba1 <unknown>\nE   #4 0x55cb8362f1f4 <unknown>\nE   #5 0x55cb836065bd <unknown>\nE   #6 0x55cb8362c5e0 <unknown>\nE   #7 0x55cb83606363 <unknown>\nE   #8 0x55cb835d2d63 <unknown>\nE   #9 0x55cb835d39c1 <unknown>\nE   #10 0x55cb83aa1a6b <unknown>\nE   #11 0x55cb83aa5951 <unknown>\nE   #12 0x55cb83a89b62 <unknown>\nE   #13 0x55cb83aa64c4 <unknown>\nE   #14 0x55cb83a6e13f <unknown>\nE   #15 0x55cb83aca6f8 <unknown>\nE   #16 0x55cb83aca8d6 <unknown>\nE   #17 0x55cb83adb5a6 <unknown>\nE   #18 0x7f75b8e9caa4 <unknown>\nE   #19 0x7f75b8f29c3c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nsrc/tests/ui_tests/test_ui_login.py:35: in test_login\n    pytest.fail(f\"❌ 로그인 실패 :{str(e)}\")\nE   Failed: ❌ 로그인 실패 :Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[contains(text(),'로그인')]\"}\nE     (Session info: chrome=135.0.7049.95); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE   Stacktrace:\nE   #0 0x55cb83adc75a <unknown>\nE   #1 0x55cb8358f4b0 <unknown>\nE   #2 0x55cb835e09b3 <unknown>\nE   #3 0x55cb835e0ba1 <unknown>\nE   #4 0x55cb8362f1f4 <unknown>\nE   #5 0x55cb836065bd <unknown>\nE   #6 0x55cb8362c5e0 <unknown>\nE   #7 0x55cb83606363 <unknown>\nE   #8 0x55cb835d2d63 <unknown>\nE   #9 0x55cb835d39c1 <unknown>\nE   #10 0x55cb83aa1a6b <unknown>\nE   #11 0x55cb83aa5951 <unknown>\nE   #12 0x55cb83a89b62 <unknown>\nE   #13 0x55cb83aa64c4 <unknown>\nE   #14 0x55cb83a6e13f <unknown>\nE   #15 0x55cb83aca6f8 <unknown>\nE   #16 0x55cb83aca8d6 <unknown>\nE   #17 0x55cb83adb5a6 <unknown>\nE   #18 0x7f75b8e9caa4 <unknown>\nE   #19 0x7f75b8f29c3c <unknown>","steps":[],"attachments":[{"uid":"9696424718b455da","name":"Failure Screenshot","source":"9696424718b455da.png","type":"image/png","size":73401},{"uid":"7a46ba14e18806e8","name":"stdout","source":"7a46ba14e18806e8.txt","type":"text/plain","size":81}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"driver::0","time":{"start":1745926047111,"stop":1745926047173,"duration":62},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"feature","value":"예외 케이스"},{"name":"story","value":"잘못된 ID,PW 입력"},{"name":"parentSuite","value":"src.tests.ui_tests"},{"name":"suite","value":"test_ui_login"},{"name":"host","value":"fv-az1971-638"},{"name":"thread","value":"2531-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"src.tests.ui_tests.test_ui_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"6b6912f2f7a5fd76.json","parameterValues":[]}