{"uid":"6f08d07b62423752","name":"test_cart","fullName":"src.tests.ui_tests.test_ui_cart#test_cart","historyId":"a5c99d53abd33890bbdde8e20d7870d0","time":{"start":1743281540988,"stop":1743281540988,"duration":0},"status":"broken","statusMessage":"TypeError: ChromeDriverManager.__init__() got an unexpected keyword argument 'cache_valid_range'","statusTrace":"@pytest.fixture(scope=\"function\")\n    def driver():\n        chrome_options = Options()\n    \n        chrome_options.add_argument(\"--disable-dev-shm-usage\") #메모리 부족 방지\n        chrome_options.add_argument(\"--no-sandbox\") #샌드박스 비활성화\n        chrome_options.add_argument(\"--headless=new\") #GUI없는 환경에서도 실행 가능\n        chrome_options.add_argument(\"--disable-gpu\")\n        chrome_options.add_argument(\"--remote-debugging-port=9222\")\n    \n        if IS_CI:\n>           service_obj = Service(ChromeDriverManager(cache_valid_range=0).install())\nE           TypeError: ChromeDriverManager.__init__() got an unexpected keyword argument 'cache_valid_range'\n\nsrc/tests/ui_tests/conftest.py:25: TypeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"driver","time":{"start":1743281540989,"stop":1743281540989,"duration":0},"status":"broken","statusMessage":"TypeError: ChromeDriverManager.__init__() got an unexpected keyword argument 'cache_valid_range'\n","statusTrace":"  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/ui_tests/conftest.py\", line 25, in driver\n    service_obj = Service(ChromeDriverManager(cache_valid_range=0).install())\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"story","value":"장바구니 화면 체크 테스트"},{"name":"feature","value":"UI 테스트"},{"name":"parentSuite","value":"src.tests.ui_tests"},{"name":"suite","value":"test_ui_cart"},{"name":"host","value":"fv-az1720-291"},{"name":"thread","value":"2513-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"src.tests.ui_tests.test_ui_cart"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"6f08d07b62423752.json","parameterValues":[]}